version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: skilluser
      POSTGRES_PASSWORD: skillpass
      POSTGRES_DB: skilllens
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: